import {applyHand, settleMatch} from './src/core.mjs';
const KEY='la-mosca-v1';
let playerCount=4; let pendingWinner=null;
const $=s=>document.querySelector(s);
function blankState(names){return {names,match:1,maxMatches:5,scores:names.map(()=>15),hands:[],totals:names.map(()=>0),history:[]};}
let state=null;
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function load(){try{return JSON.parse(localStorage.getItem(KEY))}catch{return null}}
function renderNames(){ $('#nameFields').innerHTML=Array.from({length:playerCount},(_,i)=>`<label class="nameRow"><span>${i+1}</span><input maxlength="16" placeholder="Jugador ${i+1}" value=""></label>`).join('');}
renderNames();
document.querySelectorAll('.seg button').forEach(b=>b.onclick=()=>{playerCount=+b.dataset.count;document.querySelectorAll('.seg button').forEach(x=>x.classList.toggle('active',x===b));renderNames();});
$('#start').onclick=()=>{const names=[...$('#nameFields').querySelectorAll('input')].map((x,i)=>x.value.trim()||`Jugador ${i+1}`);state=blankState(names);save();render();};
$('#newSeries').onclick=()=>{if(confirm('¿Empezar una serie nueva? Se borrará la partida actual.')){localStorage.removeItem(KEY);state=null;render();}};
function render(){const setup=!state;$('#setup').hidden=!setup;$('#game').hidden=setup;if(setup){$('#matchLabel').textContent='Nueva serie';return;}$('#matchLabel').textContent=`Partido ${state.match} de ${state.maxMatches}`;renderTable();renderHand();renderTotals();}
function cell(score,event=''){const danger=event.startsWith('CAPOTE')||event.startsWith('RENUNCIE');return `<span class="score">${score}</span>${event?`<span class="event ${danger?'danger':''}">${event}</span>`:''}`;}
function renderTable(){let h='<thead><tr><th class="handNo">Mano</th>'+state.names.map(n=>`<th>${escapeHtml(n)}</th>`).join('')+'</tr></thead><tbody>';h+='<tr><td class="handNo">Inicio</td>'+state.names.map((_,i)=>`<td>${cell(15)}</td>`).join('')+'</tr>';state.hands.forEach((hand,idx)=>{h+=`<tr><td class="handNo">${idx+1}</td>`+hand.scores.map((s,i)=>`<td>${cell(s,hand.events[i])}</td>`).join('')+'</tr>';});h+='</tbody>';$('#scoreTable').innerHTML=h;}
function renderHand(){ $('#handInputs').innerHTML=state.names.map((n,i)=>`<div class="handPlayer" data-i="${i}"><div class="pname">${escapeHtml(n)} <small>(${state.scores[i]})</small></div><input class="bases" type="number" inputmode="numeric" min="0" max="5" value="0" aria-label="Bases ${escapeHtml(n)}"><div class="toggle"><button class="play">Juega</button><button class="ren">Ren.</button></div><div class="renRow"><label>Renuncie (puntos)</label><input class="renPts" type="number" inputmode="numeric" min="1" value="15"></div></div>`).join('');
 document.querySelectorAll('.handPlayer').forEach(row=>{const play=row.querySelector('.play'), bases=row.querySelector('.bases'), ren=row.querySelector('.ren'), rr=row.querySelector('.renRow');play.dataset.playing='1';play.onclick=()=>{const playing=play.dataset.playing==='1';play.dataset.playing=playing?'0':'1';play.textContent=playing?'No juega':'Juega';play.classList.toggle('off',playing);bases.disabled=playing;if(playing)bases.value=0;updateSum();};ren.onclick=()=>rr.classList.toggle('show');bases.oninput=updateSum;});updateSum();}
function updateSum(){const sum=[...document.querySelectorAll('.handPlayer')].reduce((a,row)=>a+(row.querySelector('.play').dataset.playing==='1'?Number(row.querySelector('.bases').value||0):0),0);$('#baseSum').textContent=sum;$('#baseSum').parentElement.classList.toggle('bad',sum!==5);}
$('#saveHand').onclick=()=>{const entries=[...document.querySelectorAll('.handPlayer')].map(row=>({playing:row.querySelector('.play').dataset.playing==='1',bases:Number(row.querySelector('.bases').value||0),renuncie:row.querySelector('.renRow').classList.contains('show')?Number(row.querySelector('.renPts').value||0):0}));try{const before=structuredClone(state);const r=applyHand(state.scores,entries);state.history.push(before);state.scores=r.scores;state.hands.push({scores:[...r.scores],events:r.events,entries});save();render();const zeros=state.scores.map((s,i)=>s===0?i:-1).filter(i=>i>=0);if(zeros.length)showWinner(zeros);}catch(e){alert(e.message);}};
$('#undo').onclick=()=>{if(!state.history.length){alert('No hay una mano para deshacer.');return;}state=state.history.pop();save();render();};
function showWinner(indices){pendingWinner=indices[0];$('#winnerText').textContent=indices.length===1?`${state.names[pendingWinner]} llegó a 0.`:'Más de un jugador llegó a 0. Elegí quién ganó el partido.';$('#winnerChoices').innerHTML=indices.map(i=>`<button class="winnerChoice ${i===pendingWinner?'selected':''}" data-i="${i}">${escapeHtml(state.names[i])}</button>`).join('');document.querySelectorAll('.winnerChoice').forEach(b=>b.onclick=()=>{pendingWinner=+b.dataset.i;document.querySelectorAll('.winnerChoice').forEach(x=>x.classList.toggle('selected',x===b));});$('#winnerDialog').showModal();}
$('#closeMatch').onclick=()=>{if(pendingWinner==null)return;const delta=settleMatch(state.scores,pendingWinner);state.totals=state.totals.map((v,i)=>v+delta[i]);state.history=[];if(state.match>=state.maxMatches){$('#winnerDialog').close();save();render();alert('Serie de 5 partidos terminada. Revisá el acumulado final.');return;}state.match++;state.scores=state.names.map(()=>15);state.hands=[];pendingWinner=null;$('#winnerDialog').close();save();render();};
function renderTotals(){$('#totals').innerHTML=state.names.map((n,i)=>{const v=state.totals[i];return `<div class="totalRow"><b>${escapeHtml(n)}</b><strong class="${v>0?'positive':v<0?'negative':''}">${v>0?'+':''}${v}</strong></div>`}).join('');}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
state=load();render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js');
