document.addEventListener('DOMContentLoaded',()=>{
const KEY='la-mosca-v12';let playerCount=4,pendingWinners=[],pending=[];const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function blank(names){return{version:12,names,match:1,maxMatches:5,scores:names.map(()=>15),hands:[],totals:names.map(()=>0),matchResults:[],price:0};}let state=null;function save(){localStorage.setItem(KEY,JSON.stringify(state))}function load(){try{return JSON.parse(localStorage.getItem(KEY))}catch{return null}}
function renderNames(){$('#nameFields').innerHTML=Array.from({length:playerCount},(_,i)=>`<label class="nameRow"><span>${i+1}</span><input maxlength="14" placeholder="Jugador ${i+1}"></label>`).join('')}renderNames();document.querySelectorAll('.seg button').forEach(b=>b.onclick=()=>{playerCount=+b.dataset.count;document.querySelectorAll('.seg button').forEach(x=>x.classList.toggle('active',x===b));renderNames()});
$('#start').onclick=()=>{const names=[...$('#nameFields input')].map((x,i)=>x.value.trim()||`Jugador ${i+1}`);state=blank(names);resetPending();save();render()};$('#newSeries').onclick=()=>{if(confirm('¿Empezar una serie nueva? Se borrará la actual.')){localStorage.removeItem(KEY);state=null;render()}};
function resetPending(){pending=state?state.names.map(()=>({bases:0,skip:false,ren:false,renPoints:15})):[]}
function render(){const setup=!state;$('#setup').hidden=!setup;$('#game').hidden=setup;if(setup){$('#matchLabel').textContent='Nueva serie';return}if(pending.length!==state.names.length)resetPending();$('#matchLabel').textContent=`Partido ${state.match} de ${state.maxMatches}`;$('#handLabel').textContent=`Mano ${state.hands.length+1}`;renderPlayers();renderRecent();renderResults()}
function renderPlayers(){const box=$('#players');box.className='players'+(state.names.length===4?' four':'');box.innerHTML=state.names.map((n,i)=>{const p=pending[i],shown=p.skip||p.ren?state.scores[i]:Math.max(0,state.scores[i]-p.bases),t=state.totals[i];return `<div class="player"><div class="controls"><button class="ren ${p.ren?'active':''}" data-i="${i}">Renuncie${p.ren?' +'+p.renPoints:''}</button><button class="skip ${p.skip?'active':''}" data-i="${i}">No juega</button></div><div class="seriesDelta ${t>0?'pos':t<0?'neg':''}">${state.match>1?(t>0?'+':'')+t:'&nbsp;'}</div><div class="pname" data-i="${i}" title="Mantené apretado para editar">${esc(n)}</div><div class="points ${p.bases?'pending':''}" data-i="${i}">${shown}</div><div class="basesMini">${p.skip?'NO JUEGA':p.bases+' base'+(p.bases===1?'':'s')+(p.ren&&p.bases?' · computadas':'')}</div></div>`}).join('');box.querySelectorAll('.points').forEach(x=>x.onclick=()=>addBase(+x.dataset.i));box.querySelectorAll('.ren').forEach(x=>x.onclick=()=>{let i=+x.dataset.i;if(pending[i].skip)return;if(pending[i].ren){pending[i].ren=false;renderPlayers();return}const v=prompt(`${state.names[i]} — ¿cuántos puntos suma por RENUNCIE?`,pending[i].renPoints??15);if(v===null)return;const n=Number(v);if(!Number.isFinite(n)||n<0){alert('Ingresá una cantidad válida de puntos.');return}pending[i].ren=true;pending[i].renPoints=n;renderPlayers()});box.querySelectorAll('.skip').forEach(x=>x.onclick=()=>{let i=+x.dataset.i;pending[i].skip=!pending[i].skip;if(pending[i].skip){pending[i].bases=0;pending[i].ren=false}renderPlayers();updateSum()});bindNameLongPress(box);updateSum()}
function bindNameLongPress(box){box.querySelectorAll('.pname').forEach(el=>{let timer=null,moved=false;const cancel=()=>{if(timer)clearTimeout(timer);timer=null};const start=()=>{moved=false;cancel();timer=setTimeout(()=>{if(!moved)editPlayerName(+el.dataset.i)},650)};el.addEventListener('pointerdown',start);el.addEventListener('pointerup',cancel);el.addEventListener('pointercancel',cancel);el.addEventListener('pointerleave',cancel);el.addEventListener('pointermove',()=>{moved=true;cancel()})})}
function editPlayerName(i){const v=prompt('Nuevo nombre del jugador:',state.names[i]);if(v===null)return;const n=v.trim();if(!n){alert('El nombre no puede quedar vacío.');return}state.names[i]=n.slice(0,14);save();render()}
function addBase(i){if(pending[i].skip)return;const sum=pending.reduce((a,p)=>a+(p.skip?0:p.bases),0);if(sum>=5)return;pending[i].bases++;renderPlayers()}
function updateSum(){if(!state)return;$('#baseSum').textContent=pending.reduce((a,p)=>a+(p.skip?0:p.bases),0)}
function calcHand(scores,entries){return MoscaCore.calcHand(scores,entries)}
$('#saveHand').onclick=()=>{try{const entries=pending.map(p=>({...p})),r=calcHand(state.scores,entries);state.scores=r.scores;state.hands.push({entries,scores:[...r.scores],events:r.events});resetPending();save();render();const z=MoscaCore.resolveWinners(state.scores,entries);if(z.length)showWinner(z)}catch(e){alert(e.message)}};
$('#undo').onclick=()=>{if(!state.hands.length){alert('No hay manos para deshacer.');return}state.hands.pop();recalculateHands();resetPending();save();render()};
function recalculateHands(){let scores=state.names.map(()=>15);state.hands.forEach(h=>{const r=calcHand(scores,h.entries);scores=r.scores;h.scores=[...scores];h.events=r.events});state.scores=scores}
function tableHtml(hands,offset=0,editable=false){let h='<thead><tr><th>Mano</th>'+state.names.map(n=>`<th>${esc(n)}</th>`).join('')+(editable?'<th></th>':'')+'</tr></thead><tbody>';hands.forEach((hand,j)=>{let idx=offset+j;h+=`<tr><td>${idx+1}</td>`+hand.scores.map((s,i)=>`<td>${s}${hand.events[i]?`<div class="${/CAPOTE|RENUNCIE/.test(hand.events[i])?'danger':''}">${hand.events[i]}</div>`:''}</td>`).join('')+(editable?`<td><button class="editBtn" data-i="${idx}">Editar</button></td>`:'')+'</tr>'});return h+'</tbody>'}
function renderRecent(){const start=Math.max(0,state.hands.length-5),arr=state.hands.slice(start);$('#recentTable').innerHTML=arr.length?tableHtml(arr,start,false):'<tbody><tr><td>Todavía no hay manos cargadas.</td></tr></tbody>'}
$('#fullHistory').onclick=()=>{renderHistory();$('#historyDialog').showModal()};$('#closeHistory').onclick=()=>$('#historyDialog').close();function renderHistory(){$('#historyTable').innerHTML=state.hands.length?tableHtml(state.hands,0,true):'<tbody><tr><td>Sin manos.</td></tr></tbody>';document.querySelectorAll('.editBtn').forEach(b=>b.onclick=()=>editHand(+b.dataset.i))}
function editHand(idx){const h=state.hands[idx],parts=[];for(let i=0;i<state.names.length;i++){const e=h.entries[i];const val=prompt(`${state.names[i]} — bases (0 a 5). Escribí N para “No juega”.`,e.skip?'N':e.bases);if(val===null)return;if(String(val).trim().toUpperCase()==='N')parts.push({bases:0,skip:true,ren:false});else{const b=Number(val);if(!Number.isInteger(b)||b<0||b>5){alert('Valor inválido.');return}const ren=confirm(`${state.names[i]}: ¿tuvo RENUNCIE en esta mano?`);let renPoints=e.renPoints??15;if(ren){const rv=prompt(`${state.names[i]} — puntos por RENUNCIE:`,renPoints);if(rv===null)return;renPoints=Number(rv);if(!Number.isFinite(renPoints)||renPoints<0){alert('Valor de renuncie inválido.');return}}parts.push({bases:b,skip:false,ren,renPoints})}}try{calcHand(idx?state.hands[idx-1].scores:state.names.map(()=>15),parts);state.hands[idx].entries=parts;recalculateHands();resetPending();save();render();renderHistory();alert('Mano corregida y puntajes recalculados.')}catch(e){alert(e.message)}}
function showWinner(indices){pendingWinners=[...indices];$('#winnerText').textContent=indices.length===1?`${state.names[indices[0]]} llegó a 0 y ganó.`:`${indices.map(i=>state.names[i]).join(' y ')} llegaron a 0 con la misma cantidad de bases. El resultado se reparte.`;$('#winnerChoices').innerHTML=indices.map(i=>`<button class="winnerChoice selected" disabled>${esc(state.names[i])}</button>`).join('');$('#winnerDialog').showModal()}
function settle(scores,winners){return MoscaCore.settleShared(scores,winners)}
$('#closeMatch').onclick=()=>{if(!pendingWinners.length)return;const delta=settle(state.scores,pendingWinners);state.totals=state.totals.map((v,i)=>v+delta[i]);state.matchResults.push({match:state.match,delta:[...delta]});$('#winnerDialog').close();if(state.match<state.maxMatches){state.match++;state.scores=state.names.map(()=>15);state.hands=[];resetPending()}pendingWinners=[];save();render();if(state.matchResults.length===state.maxMatches)alert('Serie de 5 partidos terminada.')};
$('#priceBtn').onclick=()=>{const v=prompt('Precio de cada punto ($):',state.price||'');if(v===null)return;const n=Number(String(v).replace(/\./g,'').replace(',','.'));if(!Number.isFinite(n)||n<0){alert('Precio inválido.');return}state.price=n;save();renderResults()};
function money(v){return '$ '+Math.abs(v).toLocaleString('es-AR')}
function renderResults(){let html='';state.matchResults.forEach(r=>{html+=`<div class="resultBlock"><div class="resultTitle">Partido ${r.match}</div><div class="resultGrid ${state.names.length===4?'four':''}">${state.names.map((n,i)=>`<div><b>${esc(n)}</b><br><span class="${r.delta[i]>0?'positive':'negative'}">${r.delta[i]>0?'+':''}${r.delta[i]}</span></div>`).join('')}</div></div>`});$('#matchResults').innerHTML=html||'<p class="muted">Los resultados aparecerán al cerrar cada partido.</p>';$('#totals').innerHTML=`<div class="resultTitle">Acumulado · Punto: ${money(state.price)}</div>`+state.names.map((n,i)=>{const t=state.totals[i],m=t*state.price;return `<div class="totalRow"><b>${esc(n)}</b><strong class="${t>0?'positive':t<0?'negative':''}">${t>0?'+':''}${t} pts</strong><strong class="${m>0?'positive':m<0?'negative':''}">${m<0?'-':''}${money(m)}</strong></div>`}).join('')}
state=load();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');

});
